using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;
using UnityEngine.UI;
using DG.Tweening;

public class PlayerInput : MonoBehaviour
{
    [Header("ï¿½Xï¿½Lï¿½ï¿½ï¿½ÌƒNï¿½[ï¿½ï¿½ï¿½^ï¿½Cï¿½ï¿½")]
    [SerializeField] float _actionWait;
    [Header("ï¿½Xï¿½Lï¿½ï¿½Script")]
    [SerializeField] SkillSystem _skillSystem;
    [Header("Animator")]
    [SerializeField] Animator _anim;
    [Header("Playerï¿½ï¿½Sprite")]
    [SerializeField] SpriteRenderer _playerSprite;

    [Tooltip("Skillï¿½ï¿½Sprite")]
    Image _skillSprite;
    [Tooltip("ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½")]
    Vector2 _movement;
    [Tooltip("ï¿½ÅŒï¿½É“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Û‘ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½")]
    Vector2 _playerDirection;
    [Tooltip("ï¿½ï¿½ï¿½ï¿½Skillï¿½ï¿½ï¿½gï¿½ï¿½ï¿½é‚©")]
    bool _isSkill = true;
    [Tooltip("Inputï¿½ï¿½ï¿½uï¿½ï¿½ï¿½bï¿½Nï¿½ï¿½ï¿½é‚©ï¿½Ç‚ï¿½ï¿½ï¿½")]
    bool _inputBlock = false;

    Coroutine _actionCoroutine;
    WaitForSeconds _actionWaitForSeconds;

    public Material mat1;
    public Material mat2;
    public FadeSystem fs;

    void Awake()
    {
        _actionWaitForSeconds = new WaitForSeconds(_actionWait);
        _skillSprite = GameObject.Find("SkillGaugePrefab/SkillGauge").GetComponent<Image>();
        if (_skillSprite == null)
        {
            Debug.LogError("SkillSpriteï¿½ï¿½Nullï¿½Å‚ï¿½");
        }
    }

    /// <summary>ï¿½ï¿½ï¿½İƒXï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½gï¿½ï¿½ï¿½é‚©ï¿½Ç‚ï¿½ï¿½ï¿½ï¿½Ô‚ï¿½</summary>
    public bool Skill
    {
        get { return _isSkill && !_inputBlock; }
    }
    /// <summary>ï¿½ï¿½ï¿½İ‚Ì•ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Í‚ï¿½Ô‚ï¿½</summary>
    public Vector2 MoveInput
    {
        get
        {
            if (_inputBlock)
            {
                return Vector2.zero;
            }
            return _movement;
        }
    }
    void Start()
    {

    }

    void Update()
    {
        _movement = new Vector2(Input.GetAxisRaw("Horizontal"), Input.GetAxisRaw("Vertical"));

        if (_movement.x != 0 || _movement.y != 0)
        {
            _anim.SetBool("Walk", true);
            _playerDirection = _movement;
            //Playerï¿½ÌŒï¿½ï¿½ï¿½ï¿½ğ”½“]ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            if (_playerDirection.x < 0)
            {
                _playerSprite.flipX = false;
            }
            else if (_playerDirection.x > 0)
            {
                _playerSprite.flipX = true;
            }
        }
        else
        {
            _anim.SetBool("Walk", false);
        }

        if (Input.GetButtonDown("Submit") && _isSkill)
        {
            if (_actionCoroutine != null)
            {
                StopCoroutine(_actionCoroutine);
            }



            _actionCoroutine = StartCoroutine(ActionWait());
        }
    }

    /// <summary>
    /// ï¿½ï¿½ï¿½ÉƒXï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½gï¿½ï¿½ï¿½é‚½ï¿½ß‚ÌƒNï¿½[ï¿½ï¿½ï¿½^ï¿½Cï¿½ï¿½
    /// </summary>
    /// <returns></returns>
    IEnumerator ActionWait()
    {
        _isSkill = false;
        Debug.Log("ï¿½Xï¿½Lï¿½ï¿½ï¿½Jï¿½n");
        _anim.SetTrigger("Skill");


        // ãƒãƒ†ãƒªã‚¢ãƒ«åˆ‡ã‚Šæ›¿ãˆ
        _playerSprite.material = mat2;

        // yield return _actionWaitForSeconds;
        //ï¿½Xï¿½Lï¿½ï¿½ï¿½ÌƒNï¿½[ï¿½ï¿½ï¿½^ï¿½Cï¿½ï¿½ï¿½ï¿½ï¿½Ç‚ê‚­ï¿½ç‚¢ï¿½ÅIï¿½ï¿½é‚©ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½

        yield return new WaitForSeconds(1.5f);


        DOTween.To(() => 0f,
            x => _skillSprite.fillAmount = x,
            1f, _actionWait);
        _skillSystem.LightOff(_actionWait);

        Debug.Log("ï¿½Xï¿½Lï¿½ï¿½ï¿½Iï¿½ï¿½");
        _isSkill = true;

        yield return new WaitForSeconds(2f);

        // ãƒãƒ†ãƒªã‚¢ãƒ«åˆ‡ã‚Šæ›¿ãˆ
        _playerSprite.material = mat1;
    }

    /// <summary>Inputï¿½ÉŠÖ‚ï¿½ï¿½ï¿½ï¿½ï¿½Í‚ï¿½ï¿½ó‚¯•tï¿½ï¿½ï¿½é‚©ï¿½Ç‚ï¿½ï¿½ï¿½ï¿½ÏXï¿½ï¿½ï¿½ï¿½</summary>
    public void InputBlock()
    {
        Debug.Log("ï¿½Ä‚Î‚ê‚½");
        _inputBlock = !_inputBlock;
    }

    private bool clearflg = false;

    void OnTriggerEnter2D(Collider2D collision)
    {
        if(collision.gameObject.tag == "Item")
        {
            
            collision.gameObject.transform.parent = this.gameObject.transform;
            clearflg = true;
            Debug.Log("ã‚¢ã‚¤ãƒ†ãƒ ");
        }
        if(collision.gameObject.tag == "Start")
        {
            if(clearflg){
                Debug.Log("ã‚¯ãƒªã‚¢");
                fs.StartFadeOut("Success");
            }
        }
    }
}
